name: persian_datetimepickers
description: Numeric Persian (Jalali) and Gregorian date and time pickers for Flutter.
version: 1.1.0
homepage: https://github.com/gabrimatic/persian_datetimepickers
repository: https://github.com/gabrimatic/persian_datetimepickers
issue_tracker: https://github.com/gabrimatic/persian_datetimepickers/issues
topics:
  - flutter
  - dart
  - persian
  - jalali
  - datepicker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  numberpicker: ^2.1.2
  shamsi_date: ^1.1.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
